
baseURL = "https://lhnam2002.github.io/ws_FCJ_HoangNam/"
languageCode = "en-us"

title = "Serverless Data Processing Pipeline with Step Functions and EventBridge"
theme = "hugo-theme-learn"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[outputs]
home = ["HTML", "RSS", "JSON"]

[params]

  themeVariant = "workshop"


  editURL = ""
  description = "AWS workshop on building a serverless data pipeline using Step Functions and EventBridge"
  author = "journeyoftheaverageguy@gmail.com"


  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false


[Languages]

[Languages.en]
  title = "Serverless Data Processing Pipeline with Step Functions and EventBridge"
  weight = 1
  languageName = "English"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20

[Languages.vi]
  title = "Pipeline Xử Lý Dữ Liệu Serverless với Step Functions và EventBridge"
  weight = 2
  languageName = "Tiếng Việt"

  [[Languages.vi.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20
